### ISSUE TITLE
Open existing projects?

### ISSUE THREAD

**Issue by jasmingacic** [thestrukture/IDE#1]
How can it be done?

**Comment by cheikhshift** [comment]
One way of doing it is adding the existing package name under the new package dialog. By default creating a new package adds a Go server config to the specified directory, (creates new directory if not there). To build, click on `Build center` icon of your package.

**Comment by cheikhshift** [comment]
Last step (Prior to build attempt) : Click on the root of your project and update your package's type from `webapp` to `app`
![24](https://user-images.githubusercontent.com/5007086/30300455-44a4163c-9744-11e7-8078-8f0e959e9e37.png)
